/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html", "./src/**/*.{svelte,js,ts,jsx,tsx}"],
  theme: {
    extend: {},
  },
  plugins: [require("daisyui"), require('@tailwindcss/typography')],
  daisyui: {
    themes: [
      "light",
      "dark",
      "cupcake",
      "bumblebee",
      "emerald",
      "corporate",
      "synthwave",
      "retro",
      "cyberpunk",
      "valentine",
      "halloween",
      "garden",
      "forest",
      "aqua",
      "lofi",
      "pastel",
      "fantasy",
      "wireframe",
      "black",
      "luxury",
      "dracula",
      "cmyk",
      "autumn",
      "business",
      "acid",
      "lemonade",
      "night",
      "coffee",
      "winter",
      {
        med1gp: {
          primary: "#1D4A96",
          secondary: "#8b5cf6",
          accent: "#37CDBE",
          neutral: "#1c1917",
          "base-100": "#252525",
          info: "#0284c7",
          success: "#10b981",
          warning: "#eab308",
          error: "#ef4444",
          "--rounded-box": "0.5rem",
          "--rounded-btn": "0.3rem",
          // "--rounded-badge": "5",
          // "--animation-btn": "0",
          // "--animation-input": "0",
          // "--btn-text-case": "lowercase",
          // "--btn-focus-scale": "1",
          // "--tab-radius": "3rem",
        },
      },
    ],
  },
};
